apiVersion: v1
kind: Service
metadata:
  name: sampleapp1
  labels:
    app: sampleapp
spec:
  selector:
    app: sampleapp 
  ports:
  - name: NodePort
    nodePort: 32410
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  